name: Check

on:
  push:
    branches: ['*']
  pull_request:
    branches:
      - master
  schedule:
    # run every Monday at 6 AM
    - cron: '0 6 * * 1'

jobs:
  tests:
    strategy:
      matrix:
        python-version: ["3.6", "3.8", "3.10"]
        os: [ubuntu-latest, ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: "Set up Python ${{ matrix.python-version }} on ${{matrix.os}}"
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: "Run tox for ${{ matrix.python-version }}"
        run: |
          tox
    exclude: 
      - python-version: "3.10"
        os: ubuntu-20.04
      - python-version: "3.6"
        os: ubuntu-22.04
      - python-version: "3.6"
        os: ubuntu-latest
